Adding info to Mac section
theta360developers/theta-client-guide pull request #25
Opened 2023-03-20 04:55 UTC by jcasman

Intended to be merged with react-native.md file - Currently not complete but react-native-mac is not linked to the live document
Based on info from theta-client React Native tutorial and demo video

2023-03-20 16:13 UTC, codetricity requested changes
Make clickable link

```markdown
[https://github.com/ricohapi/theta-client/tree/main/react-native](https://github.com/ricohapi/theta-client/tree/main/react-native)
```

![image](https://user-images.githubusercontent.com/5799860/226401448-0c6956ff-af88-4e03-9104-74f86634bd63.png)

2023-03-21 02:12 UTC, jcasman commented on docs/react-native-mac.md
> +Use the README.md file here: https://github.com/ricohapi/theta-client/tree/main/react-native
Fixed syntax. Checked locally with mkdocs serve.

2023-03-21 15:37 UTC, codetricity approved these changes

2023-03-21 15:37 UTC, merged

2023-03-21 15:41 UTC, codetricity commented
make more progress and make another pull request

2023-03-27 00:01 UTC, jcasman commented
I am currently getting this message when I look to do a `git checkout main` and then a `git pull main`

`MacBook-Air-5:docs jcasman$ git pull
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /Users/jcasman/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/jcasman/.ssh/known_hosts:1
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

If I can solve this, I will. In the meantime, I'm working on local edits.

2023-03-27 03:53 UTC, jcasman commented
I ran `ssh-keygen -R github.com` which appears to have fixed this problem.

2023-03-27 05:21 UTC, jcasman commented
It looks like a GitHub mistake caused the problem: https://www.theregister.com/2023/03/24/github_changes_its_ssh_host/

2023-03-27 16:54 UTC, codetricity commented
I'm waiting for another pull request.